// Generated by GitHub Copilot
export type TraceSeverity = "info" | "warning" | "error";

export interface TraceEvent {
  id: string;
  timestamp: string;
  phase: string;
  detail: string;
  severity?: TraceSeverity;
}

export interface AgentTraceTimelineProps {
  events: TraceEvent[];
  title?: string;
}

/**
 * Generated by GitHub Copilot
 * Render ordered trace events for agent reasoning and tool orchestration audits.
 */
export function AgentTraceTimeline({
  events,
  title = "Agent Trace"
}: AgentTraceTimelineProps): JSX.Element {
  return (
    <section className="agui-trace" aria-labelledby="agui-trace-title">
      <h3 id="agui-trace-title">{title}</h3>
      {events.length === 0 ? <p className="agui-empty">No trace events available.</p> : null}
      <ol className="agui-trace-list">
        {events.map((event) => (
          <li key={event.id} className={`agui-trace-item agui-trace-item--${event.severity || "info"}`}>
            <p className="agui-trace-meta">
              <span>{event.timestamp}</span>
              <strong>{event.phase}</strong>
            </p>
            <p>{event.detail}</p>
          </li>
        ))}
      </ol>
    </section>
  );
}
