// Generated by GitHub Copilot
import { useMemo } from "react";

export interface ConfidenceMeterProps {
  value: number;
  label?: string;
  warningThreshold?: number;
  goodThreshold?: number;
}

/**
 * Generated by GitHub Copilot
 * Clamp confidence values to a safe range for rendering and accessibility semantics.
 */
function normalizeConfidence(value: number): number {
  return Math.max(0, Math.min(1, value));
}

/**
 * Generated by GitHub Copilot
 * Render a confidence meter with color thresholds and progressbar semantics.
 */
export function ConfidenceMeter({
  value,
  label = "Confidence",
  warningThreshold = 0.45,
  goodThreshold = 0.75
}: ConfidenceMeterProps): JSX.Element {
  const normalized = useMemo(() => normalizeConfidence(value), [value]);
  const percentage = Math.round(normalized * 100);

  const toneClass = useMemo(() => {
    if (normalized >= goodThreshold) {
      return "agui-confidence-fill--good";
    }
    if (normalized >= warningThreshold) {
      return "agui-confidence-fill--warning";
    }
    return "agui-confidence-fill--low";
  }, [goodThreshold, normalized, warningThreshold]);

  return (
    <section className="agui-confidence" aria-label={`${label} meter`}>
      <div className="agui-confidence-top">
        <strong>{label}</strong>
        <span>{percentage}%</span>
      </div>
      <div
        className="agui-confidence-track"
        role="progressbar"
        aria-valuemin={0}
        aria-valuemax={100}
        aria-valuenow={percentage}
        aria-label={label}
      >
        <div className={`agui-confidence-fill ${toneClass}`} style={{ width: `${percentage}%` }} />
      </div>
    </section>
  );
}
