// Generated by GitHub Copilot
import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { AgentTraceTimeline } from "./AgentTraceTimeline";
import { ConfidenceMeter } from "./ConfidenceMeter";
import { StreamingMessage } from "./StreamingMessage";
import { ThinkingIndicator } from "./ThinkingIndicator";
import { ToolCallVisualizer } from "./ToolCallVisualizer";

describe("agentic-ui components", () => {
    it("renders streaming message role and content", () => {
        render(<StreamingMessage role="assistant" content="Hello world" />);
        expect(screen.getByText("Assistant")).toBeInTheDocument();
        expect(screen.getByText("Hello world")).toBeInTheDocument();
    });

    it("renders tool call statuses", () => {
        render(
            <ToolCallVisualizer
                calls={[
                    {
                        id: "1",
                        name: "search",
                        status: "success",
                        latencyMs: 44
                    }
                ]}
            />
        );

        expect(screen.getByText("search")).toBeInTheDocument();
        expect(screen.getByText("success")).toBeInTheDocument();
    });

    it("renders trace events and confidence percentage", () => {
        render(
            <>
                <AgentTraceTimeline
                    events={[
                        {
                            id: "evt-1",
                            timestamp: "2026-04-28T12:00:00Z",
                            phase: "retrieval",
                            detail: "Fetched top chunks",
                            severity: "info"
                        }
                    ]}
                />
                <ConfidenceMeter value={0.72} label="Answer confidence" />
            </>
        );

        expect(screen.getByText("retrieval")).toBeInTheDocument();
        expect(screen.getByText("72%")).toBeInTheDocument();
    });

    it("renders thinking indicator states", () => {
        const { rerender } = render(<ThinkingIndicator active={false} />);
        expect(screen.getByText("Ready")).toBeInTheDocument();

        rerender(<ThinkingIndicator active={true} />);
        expect(screen.getByText("Agent is thinking")).toBeInTheDocument();
    });
});
