// Generated by GitHub Copilot
import { useEffect, useMemo, useState } from "react";

export type AgentRole = "assistant" | "user" | "system";

export interface StreamingMessageProps {
  role?: AgentRole;
  content: string;
  isStreaming?: boolean;
  revealIntervalMs?: number;
  ariaLabel?: string;
}

/**
 * Generated by GitHub Copilot
 * Convert role enum into a short UI label.
 */
function roleToLabel(role: AgentRole): string {
  if (role === "assistant") {
    return "Assistant";
  }
  if (role === "user") {
    return "User";
  }
  return "System";
}

/**
 * Generated by GitHub Copilot
 * Render a chat message with optional token-by-token reveal animation.
 */
export function StreamingMessage({
  role = "assistant",
  content,
  isStreaming = false,
  revealIntervalMs = 20,
  ariaLabel
}: StreamingMessageProps): JSX.Element {
  const [visibleLength, setVisibleLength] = useState(isStreaming ? 0 : content.length);

  const safeInterval = useMemo(() => {
    return Math.max(10, revealIntervalMs);
  }, [revealIntervalMs]);

  useEffect(() => {
    if (!isStreaming) {
      setVisibleLength(content.length);
      return;
    }

    setVisibleLength(0);
    const timer = window.setInterval(() => {
      setVisibleLength((current) => {
        if (current >= content.length) {
          window.clearInterval(timer);
          return content.length;
        }
        return current + 1;
      });
    }, safeInterval);

    return () => {
      window.clearInterval(timer);
    };
  }, [content, isStreaming, safeInterval]);

  const visibleText = content.slice(0, visibleLength);

  return (
    <article className="agui-stream-message" aria-label={ariaLabel || `${roleToLabel(role)} message`}>
      <header className="agui-stream-header">
        <span className={`agui-role-badge agui-role-badge--${role}`}>{roleToLabel(role)}</span>
      </header>
      <p className="agui-stream-content" aria-live={isStreaming ? "polite" : "off"}>
        {visibleText}
        {isStreaming && visibleLength < content.length ? (
          <span className="agui-stream-cursor" aria-hidden="true">
            ▌
          </span>
        ) : null}
      </p>
    </article>
  );
}
