// Generated by GitHub Copilot
export interface ThinkingIndicatorProps {
  active: boolean;
  label?: string;
}

/**
 * Generated by GitHub Copilot
 * Show agent processing status with animated dots and a screen-reader friendly label.
 */
export function ThinkingIndicator({
  active,
  label = "Agent is thinking"
}: ThinkingIndicatorProps): JSX.Element {
  if (!active) {
    return <span className="agui-thinking-idle">Ready</span>;
  }

  return (
    <div className="agui-thinking" role="status" aria-live="polite" aria-label={label}>
      <span className="agui-thinking-text">{label}</span>
      <span className="agui-thinking-dots" aria-hidden="true">
        <i />
        <i />
        <i />
      </span>
    </div>
  );
}
