// Generated by GitHub Copilot
export type ToolCallStatus = "pending" | "running" | "success" | "error";

export interface ToolCallItem {
  id: string;
  name: string;
  status: ToolCallStatus;
  latencyMs?: number;
  inputSummary?: string;
  outputSummary?: string;
}

export interface ToolCallVisualizerProps {
  calls: ToolCallItem[];
  title?: string;
}

/**
 * Generated by GitHub Copilot
 * Render a compact list of tool invocations with execution state and summaries.
 */
export function ToolCallVisualizer({
  calls,
  title = "Tool Calls"
}: ToolCallVisualizerProps): JSX.Element {
  return (
    <section className="agui-tool-calls" aria-labelledby="agui-tool-calls-title">
      <h3 id="agui-tool-calls-title">{title}</h3>
      {calls.length === 0 ? <p className="agui-empty">No tool calls recorded.</p> : null}
      <ul className="agui-tool-call-list">
        {calls.map((call) => (
          <li key={call.id} className={`agui-tool-call agui-tool-call--${call.status}`}>
            <div className="agui-tool-call-top">
              <strong>{call.name}</strong>
              <span className={`agui-status-chip agui-status-chip--${call.status}`}>
                {call.status}
              </span>
            </div>
            {call.latencyMs !== undefined ? (
              <p className="agui-muted">Latency: {call.latencyMs}ms</p>
            ) : null}
            {call.inputSummary ? <p className="agui-muted">Input: {call.inputSummary}</p> : null}
            {call.outputSummary ? (
              <p className="agui-muted">Output: {call.outputSummary}</p>
            ) : null}
          </li>
        ))}
      </ul>
    </section>
  );
}
