// Generated by GitHub Copilot
import { copyFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const sourcePath = join(process.cwd(), "src", "styles", "agentic-ui.css");
const targetDir = join(process.cwd(), "dist");
const targetPath = join(targetDir, "styles.css");

/**
 * Generated by GitHub Copilot
 * Copy distributed stylesheet after tsup build completes.
 */
function copyStylesheet() {
  mkdirSync(targetDir, { recursive: true });
  copyFileSync(sourcePath, targetPath);
}

copyStylesheet();
