// Generated by GitHub Copilot
import type { Preview } from "@storybook/react";

import "../src/styles/agentic-ui.css";

const preview: Preview = {
  parameters: {
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i
      }
    },
    a11y: {
      test: "todo"
    }
  }
};

export default preview;
