// Generated by GitHub Copilot
import type { Meta, StoryObj } from "@storybook/react";

import { AgentTraceTimeline } from "../src/components/AgentTraceTimeline";

const meta: Meta<typeof AgentTraceTimeline> = {
  title: "AgenticUI/AgentTraceTimeline",
  component: AgentTraceTimeline,
  args: {
    events: [
      {
        id: "e1",
        timestamp: "10:10:01",
        phase: "Intent Classification",
        detail: "Classified request as billing_refund",
        severity: "info"
      },
      {
        id: "e2",
        timestamp: "10:10:02",
        phase: "Tool Selection",
        detail: "Selected searchKnowledgeBase and policyVerifier",
        severity: "warning"
      },
      {
        id: "e3",
        timestamp: "10:10:03",
        phase: "Response Assembly",
        detail: "Generated draft response with policy citation",
        severity: "info"
      }
    ]
  }
};

export default meta;

type Story = StoryObj<typeof AgentTraceTimeline>;

export const Default: Story = {};
