// Generated by GitHub Copilot
import type { Meta, StoryObj } from "@storybook/react";

import { ConfidenceMeter } from "../src/components/ConfidenceMeter";

const meta: Meta<typeof ConfidenceMeter> = {
  title: "AgenticUI/ConfidenceMeter",
  component: ConfidenceMeter,
  args: {
    label: "Answer Confidence",
    value: 0.81
  }
};

export default meta;

type Story = StoryObj<typeof ConfidenceMeter>;

export const HighConfidence: Story = {};

export const MediumConfidence: Story = {
  args: {
    value: 0.58
  }
};

export const LowConfidence: Story = {
  args: {
    value: 0.28
  }
};
