// Generated by GitHub Copilot
import type { Meta, StoryObj } from "@storybook/react";

import { StreamingMessage } from "../src/components/StreamingMessage";

const meta: Meta<typeof StreamingMessage> = {
  title: "AgenticUI/StreamingMessage",
  component: StreamingMessage,
  args: {
    role: "assistant",
    isStreaming: true,
    revealIntervalMs: 18,
    content:
      "I analyzed your request and prepared a ranked action plan with the fastest path to impact."
  }
};

export default meta;

type Story = StoryObj<typeof StreamingMessage>;

export const Default: Story = {};

export const StaticMessage: Story = {
  args: {
    isStreaming: false
  }
};
