// Generated by GitHub Copilot
import type { Meta, StoryObj } from "@storybook/react";

import { ThinkingIndicator } from "../src/components/ThinkingIndicator";

const meta: Meta<typeof ThinkingIndicator> = {
  title: "AgenticUI/ThinkingIndicator",
  component: ThinkingIndicator,
  args: {
    active: true,
    label: "Evaluating response quality"
  }
};

export default meta;

type Story = StoryObj<typeof ThinkingIndicator>;

export const Active: Story = {};

export const Idle: Story = {
  args: {
    active: false
  }
};
