// Generated by GitHub Copilot
import type { Meta, StoryObj } from "@storybook/react";

import { ToolCallVisualizer } from "../src/components/ToolCallVisualizer";

const meta: Meta<typeof ToolCallVisualizer> = {
  title: "AgenticUI/ToolCallVisualizer",
  component: ToolCallVisualizer,
  args: {
    calls: [
      {
        id: "call-1",
        name: "searchKnowledgeBase",
        status: "success",
        latencyMs: 142,
        inputSummary: "query=refund policy",
        outputSummary: "3 matching articles"
      },
      {
        id: "call-2",
        name: "ticketLookup",
        status: "running",
        inputSummary: "ticketId=INC-20411"
      }
    ]
  }
};

export default meta;

type Story = StoryObj<typeof ToolCallVisualizer>;

export const Default: Story = {};
